# Generated by Django 2.2.9 on 2020-01-27 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='이름')),
                ('phone', models.CharField(max_length=40, verbose_name='전화번호')),
                ('address', models.CharField(max_length=100, verbose_name='주소')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='제품명')),
                ('photo', models.ImageField(upload_to='', verbose_name='제품사진')),
                ('desc', models.TextField(verbose_name='제품설명')),
                ('price', models.IntegerField(verbose_name='가격')),
                ('stock', models.IntegerField(verbose_name='남은수량')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='shop.Client', verbose_name='거래처')),
            ],
        ),
    ]
